# Generated by Django 5.2 on 2025-04-15 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ScrapedProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("price", models.CharField(max_length=50)),
                ("normal_price", models.CharField(max_length=50)),
                ("discount", models.CharField(max_length=20)),
                ("link", models.URLField(max_length=500)),
                ("description", models.TextField()),
                ("advantage", models.TextField()),
                ("category", models.CharField(max_length=100)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
